# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4488b61eb33f9c8e47cf7978a25b655d1e54a44a2f2595679a49a10bf97a3280b377469f516f323c2cd3200218259a1c7212af5a3ddb862bcd828587ed00ef53

test:
  secret_key_base: cb866985f3fdb99b55acfb6a69763ce5eecdf8e1073724629cc5ab15b2bfe0acdf437fde2604b6f1a6a0d61a5a2b544254fb0dc2b0a6677e0125661cc999edbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  s3_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
